### PR TITLE
Add more firmware versions, support MacOS

### PR DESCRIPTION
**Pull request by valievkarim**
- add more firmware versions
- support MacOS
- do not wait for download completion, instead overwrite detected file in endless loop
- change print to logging

### CODE REVIEW

**Comment by kazuki-vim** [comment]
Thanks for the PR!
Btw have you found out any firmware version that can revive our headphone?

**Comment by valievkarim** [comment]
Thanks for your work!

I think I did not have a 'no sound' bug.
My qc45 are working in general, but sometimes sound stops from my phone, and disconnecting from the second device helps (second device is macbook and it does not play any sounds at that time).

It's the same as described here:
https://www.reddit.com/r/bose/comments/18ar5vk/qc_45_issue_when_connected_to_more_than_one_device/
https://www.reddit.com/r/bose/comments/16xkaun/qc_45_2devices_static_sound_another_thread/

I think it started after an update. Before that it happened sometimes also, but rarely, and only if VLC was launched (set on pause) on my macbook.
I don't remember which version it was before, maybe I never did updates, so now I flashed `duran_encrypted_prod_1.0.3-ee3f55e.bin` and will try it

**Comment by kazuki-vim** [comment]
@valievkarim sorry I just tried your code and looks like you will continuously override the downloaded firmware _until the Update Process completed_ 
```
        while True:
            try:
                shutil.copy(firmware_path, os.path.join(monitor_directory, filepath))
                logger.info("Copied %s to %s", firmware_path, filepath)
```
Is it intended behavior?

**Comment by valievkarim** [comment]
Yes. I tried the original code once and it did not work (but i wasn't completely sure why)
I thinked that we don't need to wait for download completion, risking not to get the timing right, instead can just overwrite the file continuously

**Comment by kazuki-vim** [comment]
Understood. I think it's fine.
But probably better to stop after a certain of time, I don't want to have it continuously printing "Copied ..." :sweat_smile:

**Pull request merged**
